### PR TITLE
Update topic from sensor_data to sensors for dallas temperature sensors

### PR DESCRIPTION
**Pull request by stefboerrigter**

### CODE REVIEW

**Comment by stefboerrigter** [comment]
Sorry, forgot the description, this fixes the sensor-data which is ignored in the latest version for EMS-ESP v2.0.1 firmware.
Topic changed from sensor_data to sensors

**Comment by bbqkees** [comment]
Ok so a topic has changed once again.
But this was changed in 2.1b10 it seems not in 2.0.1.

If you can change it to `if "sensor_data" or "sensors" in topic:` then it will work for everyone with older or newer firmware.

**Comment by stefboerrigter** [comment]
added new commit to ensure compatibility, if it is OK you should be able to see it. 
i only tested with the "sensors" topic, so not tested that the old topic also works. now subscribed to both.

**Comment by bbqkees** [comment]
So I did some digging and the topic string is still 'sensor_data' in 2.1b10 so where do you see 'sensor' instead?

image

**Pull request merged**
